<a href="https://colab.research.google.com/github/hoonseong0/2026-BDA-repository/blob/main/BDA_5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8], name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [2]:
s.name

'first'

In [3]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [4]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [5]:
s.shape

(6,)

In [6]:
s.size

6

In [7]:
s[1]

np.float64(3.0)

In [9]:
s[1:5]

1    3.0
2    5.0
3    NaN
4    6.0
Name: first, dtype: float64

In [10]:
s.index = list('abcdef')

In [11]:
print(s['b'], s['d'])

3.0 nan

In [12]:
s['c':'e']

c    5.0
d    NaN
e    6.0
Name: first, dtype: float64

In [13]:
s['b':'f']

b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [14]:
s[0:3]

a    1.0
b    3.0
c    5.0
Name: first, dtype: float64

In [15]:
s1 = s[1:4]
s1

b    3.0
c    5.0
d    NaN
Name: first, dtype: float64

In [16]:
s1[0]

/tmp/ipykernel_9195/643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.float64(3.0)

In [17]:
s1[0] = 10
s1

/tmp/ipykernel_9195/1715506060.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s1[0] = 10

b    10.0
c     5.0
d     NaN
Name: first, dtype: float64

In [18]:
s

a     1.0
b    10.0
c     5.0
d     NaN
e     6.0
f     8.0
Name: first, dtype: float64

In [19]:
s.index = np.arange(1,7)
s

1     1.0
2    10.0
3     5.0
4     NaN
5     6.0
6     8.0
Name: first, dtype: float64

In [20]:
s[1]

np.float64(1.0)

In [21]:
age = pd.Series([9, 17, 32, 45, 65, 98], index=list('abcdef'), name='age')
age

a     9
b    17
c    32
d    45
e    65
f    98
Name: age, dtype: int64

In [22]:
age['b']

np.int64(17)

In [23]:
age[[1, 3, 5]]

/tmp/ipykernel_9195/1546391730.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  age[[1, 3, 5]]

b    17
d    45
f    98
Name: age, dtype: int64

In [24]:
age[['a', 'f', 'd']]

a     9
f    98
d    45
Name: age, dtype: int64

In [25]:
age[['c']]

c    32
Name: age, dtype: int64

In [26]:
s = pd.Series([3,6,-3,0, -4, 8, -7])
s

0    3
1    6
2   -3
3    0
4   -4
5    8
6   -7
dtype: int64

In [27]:
s>0

0     True
1     True
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [28]:
s%2 == 0

0    False
1     True
2    False
3     True
4     True
5     True
6    False
dtype: bool

In [29]:
s[s>0]

0    3
1    6
5    8
dtype: int64

In [30]:
s[~(s > 0)]

2   -3
3    0
4   -4
6   -7
dtype: int64

In [31]:
s[s%2 == 0]

1    6
3    0
4   -4
5    8
dtype: int64

In [32]:
s[s%2 != 0]

0    3
2   -3
6   -7
dtype: int64

In [33]:
s[(s > 0) & (s%2 == 0)]

1    6
5    8
dtype: int64

In [34]:
s = ['희빈', '수영', '현수', '지호', '지민']
p = pd.Series([99, 84, 92, 65, 78], index=s)
p

희빈    99
수영    84
현수    92
지호    65
지민    78
dtype: int64

In [37]:
p.name = '수학성적'
p.index.name = 'st_name'
p

st_name
희빈    99
수영    84
현수    92
지호    65
지민    78
Name: 수학성적, dtype: int64

In [38]:
p.sort_values()

st_name
지호    65
지민    78
수영    84
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [39]:
p.sort_values(ascending=False)

st_name
희빈    99
현수    92
수영    84
지민    78
지호    65
Name: 수학성적, dtype: int64

In [40]:
p.sort_index()

st_name
수영    84
지민    78
지호    65
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [41]:
p.sort_index(ascending=False)

st_name
희빈    99
현수    92
지호    65
지민    78
수영    84
Name: 수학성적, dtype: int64

In [42]:
p

st_name
희빈    99
수영    84
현수    92
지호    65
지민    78
Name: 수학성적, dtype: int64

In [43]:
print(p.max())
print(p.min())

99
65

In [45]:
print(p.mean())
print(p.median())

83.6
84.0

In [46]:
print(p.count())
print(p.size)

5
5

In [47]:
p.describe()

count     5.000000
mean     83.600000
std      13.088163
min      65.000000
25%      78.000000
50%      84.000000
75%      92.000000
max      99.000000
Name: 수학성적, dtype: float64

In [50]:
s = pd.Series([3, 1, 1, 2, None, np.nan, 4, 6, 6, np.nan])
s

0    3.0
1    1.0
2    1.0
3    2.0
4    NaN
5    NaN
6    4.0
7    6.0
8    6.0
9    NaN
dtype: float64

In [51]:
s.values

array([ 3.,  1.,  1.,  2., nan, nan,  4.,  6.,  6., nan])

In [53]:
s.count()

np.int64(7)

In [54]:
s.value_counts()

1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [55]:
s.value_counts(dropna=False)

NaN    3
1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [56]:
s.value_counts(sort=False, dropna=False)

3.0    1
1.0    2
2.0    1
NaN    3
4.0    1
6.0    2
Name: count, dtype: int64

In [57]:
s.value_counts(bins=4)

(0.994, 2.25]    3
(4.75, 6.0]      2
(2.25, 3.5]      1
(3.5, 4.75]      1
Name: count, dtype: int64

In [58]:
s.value_counts(bins=4, sort=False)

(0.994, 2.25]    3
(2.25, 3.5]      1
(3.5, 4.75]      1
(4.75, 6.0]      2
Name: count, dtype: int64

In [59]:
s.value_counts(bins=[0.5, 3.5, 6.5], sort=False)

(0.499, 3.5]    4
(3.5, 6.5]      3
Name: count, dtype: int64

In [61]:
df = pd.DataFrame([10,20,30,40,50])
df

    0
0  10
1  20
2  30
3  40
4  50

In [62]:
df = pd.DataFrame([[1, 2, 3],[10, 20, 30], [100, 200, 300]], index=list('abc'))
df

     0    1    2
a    1    2    3
b   10   20   30
c  100  200  300

In [64]:
df = pd.DataFrame([[1, 2, 3], [10, 20 ,30], [100, 200, 300]],
                  index=list('abc'), columns=['A', 'B', 'C'])
df

     A    B    C
a    1    2    3
b   10   20   30
c  100  200  300

In [65]:
print(df.index)
print(df.columns)

Index(['a', 'b', 'c'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')

In [66]:
df1 = pd.DataFrame(data = np.arange(12).reshape(3, 4))
df1

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [68]:
df1 = pd.DataFrame(np.random.randint(1, 46, (5, 6)))
df1

    0   1   2   3   4   5
0   2  43  26   8  25  35
1  18  17  16  20  20  42
2  17  27  21  19  39  37
3  30  10  22  26  10  17
4   5  13  24  22  45  15

In [69]:
df1 = pd.DataFrame(np.random.random((5,3)))
df1

          0         1         2
0  0.659879  0.330258  0.650081
1  0.422041  0.706994  0.081996
2  0.277647  0.618989  0.455637
3  0.389665  0.592825  0.898064
4  0.486635  0.891884  0.163927

In [70]:
df = pd.DataFrame({'국어':[82,76,67], '수학': [99, 87, 78]},
                  index=['김국진', '신영희','이길순'])
df

     국어  수학
김국진  82  99
신영희  76  87
이길순  67  78

In [71]:
df.index

Index(['김국진', '신영희', '이길순'], dtype='object')

In [72]:
df.columns

Index(['국어', '수학'], dtype='object')

In [73]:
df = pd.DataFrame({'numbers': [1, 2, 3],
                   'colors': ['red', 'white', 'blue']})
df

   numbers colors
0        1    red
1        2  white
2        3   blue

In [74]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [75]:
df.columns

Index(['numbers', 'colors'], dtype='object')

In [76]:
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
courses

fees = pd.Series([250000, 300000, 200000], name='fees')
fees

df = pd.DataFrame({courses.name: courses, fees.name: fees})
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [77]:
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
fees = pd.Series([250000, 300000, 200000], name='fees')

df = pd.concat([courses, fees], axis=1)
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [78]:
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
fees = pd.Series([250000, 300000, 200000], name='fees')

df = pd.concat([courses, fees])
df

0      Spark
1    PySpark
2     Hadoop
0     250000
1     300000
2     200000
dtype: object